name: "Setup & Install"
description: "Setup & Install"

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: "package.json"

    - name: Install Turbo
      shell: bash
      run: bun install --global turbo

    - name: Install Dependencies
      shell: bash
      run: bun install
