packages:
  - apps/*
  - packages/*
  - tooling/*

catalogs:
  # ===== BUILD TOOLS =====
  build:
    tsdown: ^0.12.3

  # ===== DEVELOPMENT TOOLS =====
  dev:
    # Git Hooks & Development Workflow
    lefthook: ^1.11.13
    
    # TypeScript & Compilation
    typescript: 5.8.3

  # ===== LINTING & FORMATTING =====
  lint:
    # Biome (ESLint/Prettier Alternative)
    "@biomejs/biome": 2.0.0-beta.5
    
    # Commit Linting
    "@commitlint/cli": ^19.8.1
    "@commitlint/config-conventional": ^19.8.1
    "@commitlint/types": ^19.8.1

  # ===== MONOREPO =====
  monorepo:
    turbo: ^2.5.3

  # ===== NODE.JS ENVIRONMENT =====
  node:
    "@clack/prompts": 1.0.0-alpha.0

  # ===== FRONTEND CORE =====
  prod:
    "@clack/core": 1.0.0-alpha.0
    picocolors: ^1.1.1

  # ===== UTILITIES =====
  utils:
    # Validation
    zod: ^3.25.28

onlyBuiltDependencies:
  - lefthook
